#define CONJUNCTION                      1
#define DISJUNCTION                      2
#define COMMENT                          3
#define NEWLINE                          4
#define ASSIGN                           5
#define LCURL                            6
#define RCURL                            7
#define COMMA                            8
#define ID                               9
#define ID_NUMBER                       10
#define EXIST                           11
#define FORALL                          12
#define LPAREN                          13
#define RPAREN                          14
#define NOT                             15
#define NOTEQUALS                       16
#define IMPLICATION                     17
#define PERIOD                          18
#define FILE_END                        19
