#define CONJUNCTION                      1
#define DISJUNCTION                      2
#define COMMENT                          3
#define NEWLINE                          4
#define ASSIGN                           5
#define LCURL                            6
#define RCURL                            7
#define COMMA                            8
#define ID                               9
#define EXIST                           10
#define FORALL                          11
#define LPAREN                          12
#define RPAREN                          13
#define NOT                             14
#define NOTEQUALS                       15
#define IMPLICATION                     16
#define WEIGHT                          17
#define PERIOD                          18
#define FILE_END                        19
